// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCubxwd8oHSNGm1NZ2cYKGbw9xECfwbo_U',
    appId: '1:231972373008:web:1a4083885857e628c48095',
    messagingSenderId: '231972373008',
    projectId: 'smart-bus-mobility',
    authDomain: 'smart-bus-mobility.firebaseapp.com',
    storageBucket: 'smart-bus-mobility.firebasestorage.app',
    measurementId: 'G-S2V25NB8MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe19949XPI_2bPQky2yDhCUUtjQWv0_2A',
    appId: '1:231972373008:android:1cf37f22b20bbbc8c48095',
    messagingSenderId: '231972373008',
    projectId: 'smart-bus-mobility',
    storageBucket: 'smart-bus-mobility.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRJXgEmE8iViYVqwl98l1S1gZ8cRFZtI',
    appId: '1:231972373008:ios:9f5885b3a2fd631bc48095',
    messagingSenderId: '231972373008',
    projectId: 'smart-bus-mobility',
    storageBucket: 'smart-bus-mobility.firebasestorage.app',
    iosBundleId: 'com.example.smartBusMobilityPlatform1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRJXgEmE8iViYVqwl98l1S1gZ8cRFZtI',
    appId: '1:231972373008:ios:9f5885b3a2fd631bc48095',
    messagingSenderId: '231972373008',
    projectId: 'smart-bus-mobility',
    storageBucket: 'smart-bus-mobility.firebasestorage.app',
    iosBundleId: 'com.example.smartBusMobilityPlatform1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCubxwd8oHSNGm1NZ2cYKGbw9xECfwbo_U',
    appId: '1:231972373008:web:2f30c4752c8b2385c48095',
    messagingSenderId: '231972373008',
    projectId: 'smart-bus-mobility',
    authDomain: 'smart-bus-mobility.firebaseapp.com',
    storageBucket: 'smart-bus-mobility.firebasestorage.app',
    measurementId: 'G-01L7E71NR1',
  );
}










