name: Flutter Android Build

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  build_apk:
    runs-on: ubuntu-latest  # Use a self-hosted runner for macOS if building for iOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Or the specific version you're using
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: Check if secrets are set
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "KEYSTORE_BASE64 is NOT set"
          else
            echo "KEYSTORE_BASE64 is set"
          fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
            echo "KEYSTORE_PASSWORD is NOT set"
          else
            echo "KEYSTORE_PASSWORD is set"
          fi
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
            echo "KEY_ALIAS is NOT set"
          else
            echo "KEY_ALIAS is set"
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "KEY_PASSWORD is NOT set"
          else
            echo "KEY_PASSWORD is set"
          fi

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk